# Generated by Django 2.2.9 on 2020-01-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='joke_text',
            field=models.CharField(max_length=3000),
        ),
    ]
