# Generated by Django 2.2.9 on 2020-02-10 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joke_recommender', '0002_auto_20200122_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate_date',
            field=models.DateTimeField(null=True, verbose_name='date rated'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
